### ISSUE TITLE
Cannot get keyboard to show up on tithe amount

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/my.newspring.cc#101] opened 2015-07-29 19:50 UTC
Replicate:
1. tap into tithe amount and put in a figure
2. close keyboard
3. open fund select
4. click tab backward - this brings up the normal iOS keyboard on tithe amount field
5. close iOS keyboard
6. tap on tithe amount - it no worky

@jbaxleyiii

**Comment by jbaxleyiii** [comment] 2015-07-29 20:03
possible duplicate of #47

**Closed** 2015-08-02 16:08 UTC
Labels: bug
