### ISSUE TITLE
On iPhone 4, the toggle indicator is fixed with scroll

### ISSUE THREAD

**Issue by benwiley** [NewSpring/my.newspring.cc#95] opened 2015-07-29 19:32 UTC
The little arrow should stay placed immediately underneath "Bank" rather than follow me as I scroll.

![image](https://cloud.githubusercontent.com/assets/8700223/8967747/e5047b54-3606-11e5-9694-2b0b4e6efb9f.png)

**Comment by jbaxleyiii** [comment] 2015-07-29 19:52
Duplicate of #74

**Comment by jbaxleyiii** [comment] 2015-07-29 19:52
Needs `position: relative` on .toggle

**Closed** 2015-08-03 18:41 UTC
Labels: duplicate
