### ISSUE TITLE
Animation on forms doesn't feel fluid

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/my.newspring.cc#66] opened 2015-07-29 18:58 UTC
*on mobile

**Comment by benwiley** [comment] 2015-08-03 19:41
@jbaxleyiii Animations all seem smooth on my phone - maybe I missed one though.  Which form did you see acting up?  On Windows phone?

**Comment by benwiley** [comment] 2015-08-03 19:44
Duplicate of #65 ?

**Closed** 2015-08-04 20:45 UTC
Labels: bug, duplicate, question
